apiVersion: v2
name: corndogs
description: A Helm chart for Kubernetes

type: application
version: 1.4.3
appVersion: "0.0.4"


dependencies:
  - name: postgresql
    version: ~12.1.6
    repository: https://charts.bitnami.com/bitnami/
    condition: postgresql.enabled
